# Generated by Django 5.1.4 on 2025-01-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0002_coffee_created_at_coffee_updated_at_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='flavor_profile',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='coffee',
            name='origin',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='coffee',
            name='roast_level',
            field=models.CharField(choices=[('L', 'Light'), ('M', 'Medium'), ('D', 'Dark')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='coffee',
            name='short_description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
