# Generated by Django 4.2.17 on 2025-01-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0007_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='hotitem',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coffee',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
