# Generated by Django 4.2.17 on 2025-01-21 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0008_coffee_hotitem_coffee_is_published'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coffee',
            new_name='Product',
        ),
    ]
